namespace BijoyBayanno
{
	// Token: 0x02000017 RID: 23
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmOptions : global::System.Windows.Forms.Form
	{
		// Token: 0x060001D1 RID: 465 RVA: 0x000D8068 File Offset: 0x000D6468
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			bool flag = disposing && this.components != null;
			if (flag)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x060001D2 RID: 466 RVA: 0x000D80A0 File Offset: 0x000D64A0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BijoyBayanno.frmOptions));
			this.TableLayoutPanel1 = new global::System.Windows.Forms.TableLayoutPanel();
			this.btnLayout = new global::System.Windows.Forms.Button();
			this.Cancel_Button = new global::System.Windows.Forms.Button();
			this.OK_Button = new global::System.Windows.Forms.Button();
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.rAM3 = new global::System.Windows.Forms.RadioButton();
			this.rAM2 = new global::System.Windows.Forms.RadioButton();
			this.rAM1 = new global::System.Windows.Forms.RadioButton();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.rWindow = new global::System.Windows.Forms.RadioButton();
			this.rGlobal = new global::System.Windows.Forms.RadioButton();
			this.chkStart = new global::System.Windows.Forms.CheckBox();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.comLayouts = new global::System.Windows.Forms.ComboBox();
			this.comKey = new global::System.Windows.Forms.ComboBox();
			this.chkShift = new global::System.Windows.Forms.CheckBox();
			this.chkCtrl = new global::System.Windows.Forms.CheckBox();
			this.chkAlt = new global::System.Windows.Forms.CheckBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TableLayoutPanel1.SuspendLayout();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.GroupBox1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.SuspendLayout();
			this.TableLayoutPanel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.TableLayoutPanel1.ColumnCount = 3;
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 52.53731f));
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 23.58209f));
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 23.58209f));
			this.TableLayoutPanel1.Controls.Add(this.btnLayout, 0, 0);
			this.TableLayoutPanel1.Controls.Add(this.Cancel_Button, 2, 0);
			this.TableLayoutPanel1.Controls.Add(this.OK_Button, 1, 0);
			global::System.Windows.Forms.Control tableLayoutPanel = this.TableLayoutPanel1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(9, 363);
			tableLayoutPanel.Location = location;
			this.TableLayoutPanel1.Name = "TableLayoutPanel1";
			this.TableLayoutPanel1.RowCount = 1;
			this.TableLayoutPanel1.RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Percent, 100f));
			global::System.Windows.Forms.Control tableLayoutPanel2 = this.TableLayoutPanel1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(335, 29);
			tableLayoutPanel2.Size = size;
			this.TableLayoutPanel1.TabIndex = 0;
			this.btnLayout.Image = global::BijoyBayanno.My.Resources.Resources.kb;
			this.btnLayout.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control btnLayout = this.btnLayout;
			location = new global::System.Drawing.Point(3, 3);
			btnLayout.Location = location;
			this.btnLayout.Name = "btnLayout";
			global::System.Windows.Forms.Control btnLayout2 = this.btnLayout;
			size = new global::System.Drawing.Size(145, 23);
			btnLayout2.Size = size;
			this.btnLayout.TabIndex = 2;
			this.btnLayout.Text = " Layout Creator/Editor...";
			this.btnLayout.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.btnLayout.UseVisualStyleBackColor = true;
			this.Cancel_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Cancel_Button.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			global::System.Windows.Forms.Control cancel_Button = this.Cancel_Button;
			location = new global::System.Drawing.Point(261, 3);
			cancel_Button.Location = location;
			this.Cancel_Button.Name = "Cancel_Button";
			global::System.Windows.Forms.Control cancel_Button2 = this.Cancel_Button;
			size = new global::System.Drawing.Size(67, 23);
			cancel_Button2.Size = size;
			this.Cancel_Button.TabIndex = 1;
			this.Cancel_Button.Text = "Cancel";
			this.OK_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			global::System.Windows.Forms.Control ok_Button = this.OK_Button;
			location = new global::System.Drawing.Point(182, 3);
			ok_Button.Location = location;
			this.OK_Button.Name = "OK_Button";
			global::System.Windows.Forms.Control ok_Button2 = this.OK_Button;
			size = new global::System.Drawing.Size(67, 23);
			ok_Button2.Size = size;
			this.OK_Button.TabIndex = 0;
			this.OK_Button.Text = "OK";
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage2);
			global::System.Windows.Forms.Control tabControl = this.TabControl1;
			location = new global::System.Drawing.Point(9, 12);
			tabControl.Location = location;
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabControl2 = this.TabControl1;
			size = new global::System.Drawing.Size(335, 345);
			tabControl2.Size = size;
			this.TabControl1.TabIndex = 1;
			this.TabPage1.Controls.Add(this.GroupBox2);
			this.TabPage1.Controls.Add(this.GroupBox1);
			this.TabPage1.Controls.Add(this.chkStart);
			global::System.Windows.Forms.TabPage tabPage = this.TabPage1;
			location = new global::System.Drawing.Point(4, 22);
			tabPage.Location = location;
			this.TabPage1.Name = "TabPage1";
			global::System.Windows.Forms.Control tabPage2 = this.TabPage1;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			tabPage2.Padding = padding;
			global::System.Windows.Forms.Control tabPage3 = this.TabPage1;
			size = new global::System.Drawing.Size(327, 319);
			tabPage3.Size = size;
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "General";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.GroupBox2.Controls.Add(this.PictureBox2);
			this.GroupBox2.Controls.Add(this.PictureBox1);
			this.GroupBox2.Controls.Add(this.rAM3);
			this.GroupBox2.Controls.Add(this.rAM2);
			this.GroupBox2.Controls.Add(this.rAM1);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			location = new global::System.Drawing.Point(10, 112);
			groupBox.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new global::System.Drawing.Size(307, 162);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = 2;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Application Mode";
			this.PictureBox2.Image = global::BijoyBayanno.My.Resources.Resources.TopBar;
			global::System.Windows.Forms.Control pictureBox = this.PictureBox2;
			location = new global::System.Drawing.Point(25, 65);
			pictureBox.Location = location;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox2;
			size = new global::System.Drawing.Size(254, 28);
			pictureBox2.Size = size;
			this.PictureBox2.TabIndex = 4;
			this.PictureBox2.TabStop = false;
			this.PictureBox1.Image = global::BijoyBayanno.My.Resources.Resources.SysTray;
			global::System.Windows.Forms.Control pictureBox3 = this.PictureBox1;
			location = new global::System.Drawing.Point(25, 121);
			pictureBox3.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox4 = this.PictureBox1;
			size = new global::System.Drawing.Size(168, 31);
			pictureBox4.Size = size;
			this.PictureBox1.TabIndex = 3;
			this.PictureBox1.TabStop = false;
			this.rAM3.AutoSize = true;
			global::System.Windows.Forms.Control rAM = this.rAM3;
			location = new global::System.Drawing.Point(6, 99);
			rAM.Location = location;
			this.rAM3.Name = "rAM3";
			global::System.Windows.Forms.Control rAM2 = this.rAM3;
			size = new global::System.Drawing.Size(247, 17);
			rAM2.Size = size;
			this.rAM3.TabIndex = 2;
			this.rAM3.Text = "System Tray (Always start as System Tray Icon)";
			this.rAM3.UseVisualStyleBackColor = true;
			this.rAM2.AutoSize = true;
			global::System.Windows.Forms.Control rAM3 = this.rAM2;
			location = new global::System.Drawing.Point(6, 42);
			rAM3.Location = location;
			this.rAM2.Name = "rAM2";
			global::System.Windows.Forms.Control rAM4 = this.rAM2;
			size = new global::System.Drawing.Size(179, 17);
			rAM4.Size = size;
			this.rAM2.TabIndex = 1;
			this.rAM2.Text = "Top Bar (Always start as Topbar)";
			this.rAM2.UseVisualStyleBackColor = true;
			this.rAM1.AutoSize = true;
			this.rAM1.Checked = true;
			global::System.Windows.Forms.Control rAM5 = this.rAM1;
			location = new global::System.Drawing.Point(6, 19);
			rAM5.Location = location;
			this.rAM1.Name = "rAM1";
			global::System.Windows.Forms.Control rAM6 = this.rAM1;
			size = new global::System.Drawing.Size(177, 17);
			rAM6.Size = size;
			this.rAM1.TabIndex = 0;
			this.rAM1.TabStop = true;
			this.rAM1.Text = "Automatic (Remember last state)";
			this.rAM1.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.rWindow);
			this.GroupBox1.Controls.Add(this.rGlobal);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox1;
			location = new global::System.Drawing.Point(10, 37);
			groupBox3.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox1;
			size = new global::System.Drawing.Size(307, 69);
			groupBox4.Size = size;
			this.GroupBox1.TabIndex = 1;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Layout Activation Mode (LAM)";
			this.rWindow.AutoSize = true;
			global::System.Windows.Forms.Control rWindow = this.rWindow;
			location = new global::System.Drawing.Point(6, 42);
			rWindow.Location = location;
			this.rWindow.Name = "rWindow";
			global::System.Windows.Forms.Control rWindow2 = this.rWindow;
			size = new global::System.Drawing.Size(301, 17);
			rWindow2.Size = size;
			this.rWindow.TabIndex = 1;
			this.rWindow.Text = "Window Based (Remember active layout for each window)";
			this.rWindow.UseVisualStyleBackColor = true;
			this.rGlobal.AutoSize = true;
			this.rGlobal.Checked = true;
			global::System.Windows.Forms.Control rGlobal = this.rGlobal;
			location = new global::System.Drawing.Point(6, 19);
			rGlobal.Location = location;
			this.rGlobal.Name = "rGlobal";
			global::System.Windows.Forms.Control rGlobal2 = this.rGlobal;
			size = new global::System.Drawing.Size(249, 17);
			rGlobal2.Size = size;
			this.rGlobal.TabIndex = 0;
			this.rGlobal.TabStop = true;
			this.rGlobal.Text = "Global (Active a layout for all windows at a time)";
			this.rGlobal.UseVisualStyleBackColor = true;
			this.chkStart.AutoSize = true;
			global::System.Windows.Forms.Control chkStart = this.chkStart;
			location = new global::System.Drawing.Point(10, 14);
			chkStart.Location = location;
			this.chkStart.Name = "chkStart";
			global::System.Windows.Forms.Control chkStart2 = this.chkStart;
			size = new global::System.Drawing.Size(216, 17);
			chkStart2.Size = size;
			this.chkStart.TabIndex = 0;
			this.chkStart.Text = "Start Bijoy Ekushe when Windows starts";
			this.chkStart.UseVisualStyleBackColor = true;
			this.TabPage2.Controls.Add(this.GroupBox3);
			global::System.Windows.Forms.TabPage tabPage4 = this.TabPage2;
			location = new global::System.Drawing.Point(4, 22);
			tabPage4.Location = location;
			this.TabPage2.Name = "TabPage2";
			global::System.Windows.Forms.Control tabPage5 = this.TabPage2;
			padding = new global::System.Windows.Forms.Padding(3);
			tabPage5.Padding = padding;
			global::System.Windows.Forms.Control tabPage6 = this.TabPage2;
			size = new global::System.Drawing.Size(327, 319);
			tabPage6.Size = size;
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "Layouts";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.Label1);
			this.GroupBox3.Controls.Add(this.comLayouts);
			this.GroupBox3.Controls.Add(this.comKey);
			this.GroupBox3.Controls.Add(this.chkShift);
			this.GroupBox3.Controls.Add(this.chkCtrl);
			this.GroupBox3.Controls.Add(this.chkAlt);
			this.GroupBox3.Controls.Add(this.Label5);
			this.GroupBox3.Controls.Add(this.Label2);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox3;
			location = new global::System.Drawing.Point(6, 6);
			groupBox5.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox3;
			size = new global::System.Drawing.Size(315, 104);
			groupBox6.Size = size;
			this.GroupBox3.TabIndex = 19;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Change Keyboard Shortcut";
			this.Label1.AutoSize = true;
			this.Label1.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(16, 25);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(87, 13);
			label2.Size = size;
			this.Label1.TabIndex = 26;
			this.Label1.Text = "Select a Layout -";
			this.comLayouts.FormattingEnabled = true;
			global::System.Windows.Forms.Control comLayouts = this.comLayouts;
			location = new global::System.Drawing.Point(140, 22);
			comLayouts.Location = location;
			this.comLayouts.Name = "comLayouts";
			global::System.Windows.Forms.Control comLayouts2 = this.comLayouts;
			size = new global::System.Drawing.Size(158, 21);
			comLayouts2.Size = size;
			this.comLayouts.TabIndex = 25;
			this.comKey.Enabled = false;
			this.comKey.FormattingEnabled = true;
			global::System.Windows.Forms.Control comKey = this.comKey;
			location = new global::System.Drawing.Point(257, 53);
			comKey.Location = location;
			this.comKey.Name = "comKey";
			global::System.Windows.Forms.Control comKey2 = this.comKey;
			size = new global::System.Drawing.Size(41, 21);
			comKey2.Size = size;
			this.comKey.TabIndex = 24;
			this.chkShift.AutoSize = true;
			this.chkShift.Enabled = false;
			this.chkShift.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			global::System.Windows.Forms.Control chkShift = this.chkShift;
			location = new global::System.Drawing.Point(200, 55);
			chkShift.Location = location;
			this.chkShift.Name = "chkShift";
			global::System.Windows.Forms.Control chkShift2 = this.chkShift;
			size = new global::System.Drawing.Size(56, 17);
			chkShift2.Size = size;
			this.chkShift.TabIndex = 23;
			this.chkShift.Text = "Shift +";
			this.chkShift.UseVisualStyleBackColor = true;
			this.chkCtrl.AutoSize = true;
			this.chkCtrl.Enabled = false;
			this.chkCtrl.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			global::System.Windows.Forms.Control chkCtrl = this.chkCtrl;
			location = new global::System.Drawing.Point(151, 55);
			chkCtrl.Location = location;
			this.chkCtrl.Name = "chkCtrl";
			global::System.Windows.Forms.Control chkCtrl2 = this.chkCtrl;
			size = new global::System.Drawing.Size(50, 17);
			chkCtrl2.Size = size;
			this.chkCtrl.TabIndex = 22;
			this.chkCtrl.Text = "Ctrl +";
			this.chkCtrl.UseVisualStyleBackColor = true;
			this.chkAlt.AutoSize = true;
			this.chkAlt.Enabled = false;
			this.chkAlt.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			global::System.Windows.Forms.Control chkAlt = this.chkAlt;
			location = new global::System.Drawing.Point(106, 55);
			chkAlt.Location = location;
			this.chkAlt.Name = "chkAlt";
			global::System.Windows.Forms.Control chkAlt2 = this.chkAlt;
			size = new global::System.Drawing.Size(47, 17);
			chkAlt2.Size = size;
			this.chkAlt.TabIndex = 21;
			this.chkAlt.Text = "Alt +";
			this.chkAlt.UseVisualStyleBackColor = true;
			this.Label5.AutoSize = true;
			this.Label5.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			global::System.Windows.Forms.Control label3 = this.Label5;
			location = new global::System.Drawing.Point(69, 80);
			label3.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label4 = this.Label5;
			size = new global::System.Drawing.Size(231, 13);
			label4.Size = size;
			this.Label5.TabIndex = 20;
			this.Label5.Text = "e.g.- Alt + Ctrl + B (Shortcut key will be blocked)";
			this.Label2.AutoSize = true;
			this.Label2.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			global::System.Windows.Forms.Control label5 = this.Label2;
			location = new global::System.Drawing.Point(16, 56);
			label5.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label6 = this.Label2;
			size = new global::System.Drawing.Size(74, 13);
			label6.Size = size;
			this.Label2.TabIndex = 19;
			this.Label2.Text = "Shortcut Key -";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(352, 401);
			this.ClientSize = size;
			this.Controls.Add(this.TabControl1);
			this.Controls.Add(this.TableLayoutPanel1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "frmOptions";
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Options";
			this.TableLayoutPanel1.ResumeLayout(false);
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.TabPage2.ResumeLayout(false);
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.ResumeLayout(false);
		}

		// Token: 0x040000F9 RID: 249
		private global::System.ComponentModel.IContainer components;
	}
}
